### ISSUE TITLE
Feature Request: Create Material Pass Takes

### ISSUE THREAD

**Issue by enols** [aturtur/cinema4d-scripts#11]
Hey @aturtur. Appreciate the time and effort you put in to maintaining this project. 

Would it be possible to add a material pass option - one that when selecting a group of materials in materials manager will then automatically create a set of takes where all other materials are overrided to off and the selected one is white?

**Comment by aturtur** [comment]
Good idea. It's now on my to do list.

**Comment by aturtur** [comment]
Added in v1.77
