### ISSUE TITLE
Feature Request : Export selected objects as individual c4d files

### ISSUE THREAD

**Issue by RanArkon** [aturtur/cinema4d-scripts#13]
Hello,

Main problem with working in large scenes in Cinema 4D is that if we change materials for many objects there is no way to update them on disk where they was loaded because Cinema 4D store objects in one scene file and XRef system is totally buggy. 

So my question is there way to create script that will export all selected objects as different c4d files so we can update, move them manually to corresponding folders after that. And it would be great that objects connected to parent ( for example null ) would be treated as one c4d file.

Best Regards,
Sebastian

**Comment by aturtur** [comment]
AR_ExportC4D.py script might be what you are looking for?

**Comment by RanArkon** [comment]
Ah yes, it works perfectly ! I didn't saw it before :) Thank you !
