### ISSUE TITLE
Feature Request : name of material tag from its material name

### ISSUE THREAD

**Issue by RanArkon** [aturtur/cinema4d-scripts#14]
Hi,

It would be great to have script to name material tag from its material name :
![image](https://github.com/aturtur/cinema4d-scripts/assets/77547152/ca2328c0-5e47-420e-88c6-bc26793554bd)

Also for changing selection name from material to its material name
![image](https://github.com/aturtur/cinema4d-scripts/assets/77547152/b2de19a4-a615-4731-ad5d-a8512392ec54)

**Comment by aturtur** [comment]
This is very specific case of script. I'm thinking creating misc folder where I put these kind of special scripts that are not so general. Otherwise script pack will get super bloated.

**Comment by aturtur** [comment]
These scripts can be found under [misc](https://github.com/aturtur/cinema4d-scripts/tree/master/Misc) folder
