### ISSUE TITLE
Feature Request - Save modified ( or all ) XRef's

### ISSUE THREAD

**Issue by RanArkon** [aturtur/cinema4d-scripts#16]
It would be great to have option to save modified XRef objects, materials to their references. At the moment if we change something in XRef there is no way to save these changes to original reference object. Open for edit doesn't store changes - it reset all XRef parameters to reference default.

**Comment by aturtur** [comment]
I never use XRefs and I'm having hard time figuring out what is the main issue here.

**Comment by RanArkon** [comment]
If we have Xref object loaded, if we change something in its material ( for example texture brightness ) it is not saved in Xref file but in scene file. So if we load this Xref again, it will still have old default material.

Generally in other software changing made to Xref in one scene should be the same in new scenes - this is what Xref is for.

I reported some time ago to Maxon that they should have button like - save changes to XRef or update changed XRefs.

**Comment by aturtur** [comment]
Hopefully Maxon will fix this. I don't wanna touch Xrefs.
