### ISSUE TITLE
Script Idea: Markers to Range

### ISSUE THREAD

**Issue by h3llolovely** [aturtur/cinema4d-scripts#17]
Hello,  
I have an idea for a script.
I tried to make it myself, but realized it was beyond my abilities. So I am officially giving up.
I'd like to give it to you because I think it would be a useful feature and I know you can make it even better.
Thank you.

Here it is...

## Markers to Range

**Description:**
Retrieves marker info (Name, calculates the From/To values in frames, whether marker is selected or not), stores those values in a dictionary to pass to selected render settings via a dockable gui interface with a selectable list of markers next to a mirrored list of the documents render settings. Then set the selected Render Setting Range to that of the selected Marker.

**Proposed Workflow:**
- Open a dockable gui dialog box. (see mockup image)
- Populate a selectable list of the Timeline Markers.
- Populate a selectable list of the Documents Render Settings.
- Create a "Refresh Markers" button to reload Timeline Markers.
- Select the desired Marker, then Select the desired Render Setting.
- Click "Set Range" (Frame Range mode is set to "manual", From / To values are set from the selected Marker's range)
- Repeat to apply to other Render Settings

---

**Example Timeline Markers:**

![Timeline_Markers](https://github.com/aturtur/cinema4d-scripts/assets/101287022/957ccc71-b194-441a-b0f8-ac67b4c1880c)

**GUI Mockup:**

![MarkersToRange_Mockup](https://github.com/aturtur/cinema4d-scripts/assets/101287022/92f0d16d-e5ca-4b29-b99d-9a469b370140)

**Changed Render Settings:**

![RenderSettings](https://github.com/aturtur/cinema4d-scripts/assets/101287022/1cbae260-7137-4ce1-bc45-c2d2149cbeb3)

**Comment by aturtur** [comment]
Thanks for the request and very comprehensive explanation. I'll take a look.

**Comment by aturtur** [comment]
This is done and will be added in the next version of AR_Scripts
