### ISSUE TITLE
Bug report - Markers to Range

### ISSUE THREAD

**Issue by h3llolovely** [aturtur/cinema4d-scripts#19]
Hi Aturtur,
Thank you for creating this script. 
I noticed a small inconsistency in how the marker's range is calculated as well as a fraction frame number is added to the "To" range.

In this example, there are 2 frame spans 0-12 and 16-20
![01](https://github.com/user-attachments/assets/baab5791-6b8b-42ae-b5b0-b217fa132e17)

The Project and Render Setting FPS are synced at 24fps
![02](https://github.com/user-attachments/assets/592116e2-3594-4c67-8f85-79213bf4f743)

Bug 1: You can see that Markers to Range reports the end frame of each span as 1 frame short. (i.e. 11, instead of 12; 19, instead of 20)
Bug 2: When Set Range is clicked, It sets Range "To" to a fractional value of +/- 0.01/frame
![03](https://github.com/user-attachments/assets/ae624862-7566-4dac-abda-7336bbea0e1d)
![04](https://github.com/user-attachments/assets/817d1375-b807-43a5-aab9-0914962435fb)

Thank you again for your work.
I just wanted to bring this to you attention.

**Comment by aturtur** [comment]
Thanks for the report. Bugs are now fixed. I just uploaded hotfix
