### ISSUE TITLE
AR_ToggleTintedBorder - Python 3 R23 decode error

### ISSUE THREAD

**Issue by msanity** [aturtur/cinema4d-scripts#2]
Hi!
In R23, I get an error with this script: 

 > Traceback (most recent call last):
>   File "C:\Users\michael.walz\AppData\Roaming\Maxon\Maxon Cinema 4D R23_DBA5903C\library\scripts\AR_Scripts_1.0.6\AR_ToggleTintedBorder.py", line 104, in <module>
>     main()
>   File "C:\Users\michael.walz\AppData\Roaming\Maxon\Maxon Cinema 4D R23_DBA5903C\library\scripts\AR_Scripts_1.0.6\AR_ToggleTintedBorder.py", line 63, in main
>     f = open(data.decode('utf-8')) # Open file for reading
> AttributeError: 'str' object has no attribute 'decode'

I believe in Python 3 the decode is not necessary, so by removing the 3 instances of ".decode('utf-8')" it was working again.

Thank you for the fantastic scripts!

**Comment by aturtur** [comment]
Cheers! Scripts are made for Cinema 4D R21 and Python 2.7.14. It's expected that there are some compatibility issues with R23 and Python 3. I don't have R23 so I can't update or test my scripts for that version.
