### ISSUE TITLE
Cannot find the AR_AxisToCenter script.

### ISSUE THREAD

**Issue by Anlv-max** [aturtur/cinema4d-scripts#20]
As the title suggests, the AR_AxisToCenter script cannot be found in the 1.78 folder. I tried a global search and only found it in the R21 folder, but its last update was two years ago, so it is not a new script.

**Comment by aturtur** [comment]
That script is marked as deprecated. C4D's native "Axis Center" tool does everything it does and more. What functionality you are looking for?

**Comment by Anlv-max** [comment]
Sorry bro, I saw this update
**04.07.2024 Updated: AR_AxisToCenter, doesn't change children transformations**
So some questions arose.

I will close this issue later.

Changes in 1.78

09.07.2024 New script: AR_ZoomHelper (Camera)
04.07.2024 New script: AR_AxisToParent (Modeling)
**04.07.2024 Updated: AR_AxisToCenter, doesn't change children transformations**
27.06.2024 New script: AR_MarkersToRange (Animation)
26.04.2024 New script: AR_TakeMarkSelected, AR_TakeUnmarkSelected, AR_TakeMarkToggleSelected (Takes)
26.04.2024 Updated: AR_BakePLA and AR_BakePSR, disables alembic morph tag on baked object(s)
10.04.2024 Updated: AR_TglEnable, added support for new 2024.4.0 particle objects and Thicken generator and Doodle object
20.02.2024 New script: AR_PrintCloneCount (Utility)
20.02.2024 Updated: AR_LayerToggle, AR_LayerOff, AR_LayerOn, added undo support
17.01.2024 Updated: AR_KeysConstantSpeed, error checking
12.01.2024 New script: AR_EdgeSelectionsToSpline (Modeling)
10.01.2024 New script: AR_EditorCamToSelectedCam (Camera)
10.01.2024 New script: AR_SelectedCamToEditorCam (Camera)
26.12.2023 New script: AR_TakeMaterialPreviews (Take)
Older change logs are collected in [CHANGELOG.md](https://github.com/aturtur/cinema4d-scripts/blob/master/CHANGELOG.md) file

**Comment by aturtur** [comment]
Oh, that's just my mistake, sorry. Will edit it later
