### ISSUE TITLE
Features-Request: Take a look and decide, if you want to implement from this collection of scripts

### ISSUE THREAD

**Issue by vacterro** [aturtur/cinema4d-scripts#23]
Hi Aturtur!

Have insipired by your scripts. I'd like to share with You some self-maded scripts, that, in my opinion, would like to have some interest for you to implement in Your collection of scripts for Cinema 4D. Take a look.

https://github.com/vacterro/vac34_c4d_scripts

**Comment by aturtur** [comment]
Hi, thanks! I'll take a look and consider that.
