### ISSUE TITLE
AR_KeysConstantSpeed Improvement

### ISSUE THREAD

**Issue by StudioVakuum** [aturtur/cinema4d-scripts#28]
Hi, I suggest changing 

        if len(keys) == 0:
            return False

to

        if len(keys) < 1:
            continue
            
That way, you can also apply the script on just one timeline like Position . Z instead of selecting other keyframes under the same "timeline group" (e.g. Position . Y and Position . X). Or apply on two timelines. You're just more flexible like this.

**Comment by aturtur** [comment]
Thanks for the improvement suggestion. I'm modifying this to the next version.
