### ISSUE TITLE
AR_OpenRenderFolder

### ISSUE THREAD

**Issue by Anlv-max** [aturtur/cinema4d-scripts#4]
Dear Arttu Rautio.
I've been using it Cinema 4D R26.
I found out AR_OpenRenderFolder 1.0 Able to open the directory normally "./render/$prj"
But AR_OpenRenderFolder 1.0.4 Not working.

**Comment by aturtur** [comment]
Hi, are you using C4D with Windows or Mac? In Windows, Cinema 4D automatically corrects the path from "./render/$prj" to "render/$prj" and that opens correctly with the AR_OpenRenderFolder script.

Remove "./" from your path and test if that works!

**Comment by Anlv-max** [comment]
Thank you very much, according to your reminder, it works!
