### ISSUE TITLE
AR_Folder not working in 2023

### ISSUE THREAD

**Issue by hurricanz** [aturtur/cinema4d-scripts#5]
\Utility\AR_Folder.py", line 573, in createFolderNull
    null[c4d.NULLOBJECT_ICONCOL] = True
AttributeError: module 'c4d' has no attribute 'NULLOBJECT_ICONCOL'

**Comment by aturtur** [comment]
Hi! Thanks for the heads up. AR_Folder is now updated with support for Cinema 4D 2023 in AR_Scripts_1.68_R25
