### ISSUE TITLE
AR_Selection tools (hotkey-able?)

### ISSUE THREAD

**Issue by hurricanz** [aturtur/cinema4d-scripts#6]
I tried creating hotkeys for the AR_Selection tools which would be useful when selecting maybe a Sweep in the Viewport, then using a hotkey for AR_SelectDown to go into the Sweep hierarchy, then AR_SelectNext to select the spline to edit in the viewport.     It doesn't seem to work.   

The only way it sort of works is if I move my mouse over the Object Manager and then use the hotkeys to use AR_SelectDown.   But then it's a bit confusing because AR_SelectNext (or Prev) doesn't work with the hotkeys as I would think.  I can just use AR_SelectDown  (or SelectUp) continuously to select the object above or below.     Moving my mouse away from the object in the viewport is obviously not efficient and i might as well just use the buttons on a palette.

**Comment by aturtur** [comment]
Hi, what Cinema 4D version are you using? At least in Cinema 4D 2023.1.0 you can use hotkeys when the mouse cursor is over the viewport and the scripts works correctly.

Some selection scripts uses keyboard modifiers (e.g. shift, ctrl): Shift adds to the current selection and Ctrl removes from the selection. This is universal in most of the applications. If you have binded hotkey with a shift or ctrl it triggers keyboard modifier feature in the script. If you do not want to use script's keyboard modifier features you have disable them by modifying the script.

**Comment by hurricanz** [comment]
ahh good to know!!!! Thanks for such quick reponses!

**Comment by aturtur** [comment]
This is now fixed in [AR_Scripts_1.70](https://github.com/aturtur/cinema4d-scripts/tree/master/AR_Scripts_1.70)
