### ISSUE TITLE
Ideas for your script collection

### ISSUE THREAD

**Issue by Vannipo** [aturtur/cinema4d-scripts#7]
Hello Aturtur,

i really appreciate your hard work and offering your wonderful scripts, which make the C4D life a bit easier for all of us!
I am coming from Softimage, one of the most intuitive 3D tools out there. Sadly, Autodesk canceled the development. :(

As animator there are 2 workflows I really miss in C4D:

1.
The missing feature to add keyframes to Pos/Rot/Scale separately for X or Y or Z by just pressing a hotkey for each one of them. Means, 9 scripts, each of them just adds a key for one track of the current selection of objects. Then it would be possible to assign hotkeys the each of those scripts and would make it possible to key only the parameter of SRT I want to key. This would make the workflow so much faster!

It would replace the workaround doing this in the attribute manager by clicking with the mouse:
![Anmerkung 2023-01-08 210658](https://user-images.githubusercontent.com/76270473/211216617-e0182a07-365c-47a2-9de2-e49828f55c54.png)

2.
A simple "Match All Transforms".
Matches the global SRT of the selected objects to one single target object. I don't know, whether a pick session is possible in C4D. If not, this could be done by selecting the target object as the last one.
This could be extended to scripts matching only the translation (position), rotation and scaling.
"Match Translation"
"Match Rotation"
"Match Scaling"

This would replace the workflow, where u can make an object a child and set SRT to 0.0 and put it back, where it was before in the hirarchy. Or to temporarily constrain an object to another and delete the constraint again.

_Edit:_
Oh my goodness,
I just explored the "Transfer"-tool. Ok, forget about my 2nd idea! 

I wish I could code like you. But I am just too dumb for this. :)

Kind regards
Vannipo

**Comment by aturtur** [comment]
Hi, thanks for the script suggestions. These are now added in [AR_Scripts_1.71](https://github.com/aturtur/cinema4d-scripts/tree/master/AR_Scripts_1.71)

**Comment by Vannipo** [comment]
A bit late, but:

You are awesome! It works exactly as it should. You really did it. Thank you very much.
