### ISSUE TITLE
AR_ImportImageFolder.py Error

### ISSUE THREAD

**Issue by apetown** [aturtur/cinema4d-scripts#8]
I ran into an issue where the script would make a material for every texture instead of putting the respective textures into the channels of one material. all the texture share the same. Unfortunately i don't know enough about the API to really debug it but I figured if I followed the standard materials channel  names and called them in the same manner that you setup it ideally should work. 
in the images you can see it is just defaulting to the color channel.
base name_[Channel].png

any insight would be helpful, Im sure its something im missing.
![Screenshot 2023-06-07 194519](https://github.com/aturtur/cinema4d-scripts/assets/7075519/91cb5692-37a7-43d6-8700-8676f522bb1c)
![Screenshot 2023-06-07 194841](https://github.com/aturtur/cinema4d-scripts/assets/7075519/cc38ef1e-57b0-499e-9516-3fd70ae46803)

**Comment by aturtur** [comment]
AR_ImportImageFolder script's function is to make material for every image file it finds from the folder. It does not support different channels on file path name's. To make it work with channels the script has to parse the file name and link texture to the corresponding channel. I have done something pretty similar with [AR_NodeTexToMat](https://github.com/aturtur/cinema4d-scripts/blob/master/AR_Scripts_1.74/Node%20Tools/AR_NodeTexToMat.py) script. But this is not really an error, it's a feature.
